### ISSUE TITLE
magick-cli on AWS Lambda

### ISSUE THREAD

**Issue by merla** [NickNaso/magick-cli#13]
I am trying to resize image using native image magick-cli.  It is working fine in my mac. When I upload the zipped code to AWS lambda, it is failing with error 
`module initialization error: Error
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/var/task/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/var/task/node_modules/magick-cli/lib/magick-cli.js:25:38)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)`

Does the node modules of mac binaries not sufficient for execution of lambda? How to install magick-cli on lambda.

**Comment by NickNaso** [comment]
Hi @merla ,
I think that the binary for mac is not good and you need the binary for linux. I found this guide provided by Amazon that explain how to install native add-on to be use in AWS Lambda. 
https://aws.amazon.com/blogs/compute/nodejs-packages-in-lambda/

**Comment by merla** [comment]
Hi Nick. Thanks for providing the info. Will try it out.

**Comment by NickNaso** [comment]
@merla Keep me updated if it worked for you.
